### ISSUE TITLE
[Bug]:Closing button is not visible in  message section.

### ISSUE THREAD

**Issue by itzamanjain** [tembo-io/website#380]
Steps to reproduce:
1. Go to https://cloud.tembo.io/orgs/org_2cimlu8W2kJV0rS7NLcwJdu4BqM/clusters
2. On the message, we don't see a closing button because it is white, but when we hover on it, it becomes light grayish.

Expected behavior:
1. The closing button should be black for a better user interface.

current behavior :
![Screenshot from 2024-02-27 12-36-29](https://github.com/tembo-io/website/assets/145151053/1fa67761-c34d-4bd6-b4c8-df9c6f41946c)
![Screenshot from 2024-02-27 12-38-29](https://github.com/tembo-io/website/assets/145151053/3df400fd-07e9-4e54-8914-47ca726c86fc)

**Comment by DarrenBaldwin07** [comment]
Thank you for opening!
